on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      VERSION: ${{ github.ref_name }}
    steps:
      - run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >> ~/.ssh/config << END
          Host github
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            StrictHostKeyChecking no
          END
      - run: ssh -i ~/.ssh/github github 'cd /docker/scheduler-express && echo "VERSION=$VERSION" > .env && sudo docker compose up -d scheduler-prod'
